name: CI

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main

jobs:
  build_windows:
    name: Build Windows Desktop
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Build ChatGPT.UI.Desktop
      run: dotnet build src/ChatGPT.UI.Desktop/ChatGPT.UI.Desktop.csproj --configuration Release
  build_windows_browser:
    name: Build Windows Browser
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install workloads
      run: dotnet workload install wasm-tools wasm-experimental
    - name: Build ChatGPT.UI.Browser
      run: dotnet build src/ChatGPT.UI.Browser/ChatGPT.UI.Browser.csproj --configuration Release
  build_windows_android:
    name: Build Windows Android
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install workloads
      run: dotnet workload install android
    - name: Build ChatGPT.UI.Android
      run: dotnet build src/ChatGPT.UI.Android/ChatGPT.UI.Android.csproj --configuration Release
  build_windows_ios:
    name: Build Windows iOS
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install workloads
      run: dotnet workload install ios
    - name: Build ChatGPT.UI.iOS
      run: dotnet build src/ChatGPT.UI.iOS/ChatGPT.UI.iOS.csproj --configuration Release
  build_linux_desktop:
    name: Build Ubuntu Desktop
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Build ChatGPT.UI.Desktop
      run: dotnet build src/ChatGPT.UI.Desktop/ChatGPT.UI.Desktop.csproj --configuration Release
  build_linux_android:
    name: Build Ubuntu Android
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install workloads
      run: dotnet workload install android
    - name: Build ChatGPT.UI.Android
      run: dotnet build src/ChatGPT.UI.Android/ChatGPT.UI.Android.csproj --configuration Release
  build_linux_browser:
    name: Build Ubuntu Browser
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install workloads
      run: dotnet workload install wasm-tools wasm-experimental
    - name: Build ChatGPT.UI.Browser
      run: dotnet build src/ChatGPT.UI.Browser/ChatGPT.UI.Browser.csproj --configuration Release
  build_macos_desktop:
    name: Build macOS Desktop
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Build ChatGPT.UI.Desktop
      run: dotnet build src/ChatGPT.UI.Desktop/ChatGPT.UI.Desktop.csproj --configuration Release
  build_macos_ios:
    name: Build macOS iOS
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install workloads
      run: dotnet workload install ios
    - name: Build ChatGPT.UI.iOS
      run: dotnet build src/ChatGPT.UI.iOS/ChatGPT.UI.iOS.csproj --configuration Release
  build_macos_browser:
    name: Build macOS Browser
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install workloads
      run: dotnet workload install wasm-tools wasm-experimental
    - name: Build ChatGPT.UI.Browser
      run: dotnet build src/ChatGPT.UI.Browser/ChatGPT.UI.Browser.csproj --configuration Release
